name: CI
on: [push, pull_request]
env:
  GO_VERSION: '1.25'
  STATIC_CHECK_VERSION: '2025.1.1'
jobs:
  format:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check format
        run: |
          source ./run.sh
          dirty_files="$(run::format)"
          if [[ "${dirty_files}" != "" ]]; then $(exit 1); fi
      - name: Run linters
        run: |
          go install "honnef.co/go/tools/cmd/staticcheck@${STATIC_CHECK_VERSION}"
          source ./run.sh
          run::lint
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Print info about environment
        run: go version
      - name: Install dependencies
        run: source ./run.sh && run::install
      - name: Run unit tests
        run: source ./run.sh && run::test
